// Auto-generated by scripts/generate_content_page.py
// Run the script to update this file with the latest module data.

export interface YearModule {
  id: number;
  title: string;
  questionCount: number;
  chapterCount: number;
  gradient: string;
}

export interface YearData {
  year: string;
  totalQuestions: number;
  moduleCount: number;
  modules: YearModule[];
}

export const yearData: YearData[] = [
  {
    year: '1ère année',
    totalQuestions: 2315,
    moduleCount: 5,
    modules: [
    { id: 7, title: 'Histologie Embryologie', questionCount: 125, chapterCount: 19, gradient: 'from-blue-400 to-blue-600' },
    { id: 8, title: 'Anatomie 2', questionCount: 513, chapterCount: 20, gradient: 'from-green-400 to-green-600' },
    { id: 9, title: 'Physiologie 1', questionCount: 679, chapterCount: 30, gradient: 'from-purple-400 to-purple-600' },
    { id: 10, title: 'Hématologie', questionCount: 492, chapterCount: 32, gradient: 'from-red-400 to-red-600' },
    { id: 11, title: 'Microbiologie - Virologie - Immunologie', questionCount: 506, chapterCount: 48, gradient: 'from-yellow-400 to-yellow-600' }
    ]
  },
  {
    year: '2ème année',
    totalQuestions: 3007,
    moduleCount: 7,
    modules: [
    { id: 1, title: 'Pharmacologie', questionCount: 612, chapterCount: 31, gradient: 'from-blue-400 to-blue-600' },
    { id: 3, title: 'Anatomo-pathologie 1', questionCount: 266, chapterCount: 20, gradient: 'from-purple-400 to-purple-600' },
    { id: 4, title: 'Sémiologie 2', questionCount: 648, chapterCount: 44, gradient: 'from-green-400 to-green-600' },
    { id: 5, title: 'Radiologie', questionCount: 451, chapterCount: 33, gradient: 'from-red-400 to-red-600' },
    { id: 6, title: 'Biochimie clinique', questionCount: 297, chapterCount: 22, gradient: 'from-yellow-400 to-yellow-600' },
    { id: 12, title: 'Anatomo-pathologie 2', questionCount: 287, chapterCount: 18, gradient: 'from-indigo-400 to-indigo-600' },
    { id: 13, title: 'Parasitologie Mycologie Maladies Infectieuses', questionCount: 446, chapterCount: 30, gradient: 'from-pink-400 to-pink-600' }
    ]
  },
  {
    year: '3ème année',
    totalQuestions: 2590,
    moduleCount: 5,
    modules: [
    { id: 1, title: 'Pharmacologie', questionCount: 612, chapterCount: 31, gradient: 'from-blue-400 to-blue-600' },
    { id: 2, title: 'Cardiologie', questionCount: 815, chapterCount: 40, gradient: 'from-green-400 to-green-600' },
    { id: 3, title: 'Anatomo-pathologie 1', questionCount: 266, chapterCount: 20, gradient: 'from-purple-400 to-purple-600' },
    { id: 5, title: 'Radiologie', questionCount: 451, chapterCount: 33, gradient: 'from-red-400 to-red-600' },
    { id: 13, title: 'Parasitologie Mycologie Maladies Infectieuses', questionCount: 446, chapterCount: 30, gradient: 'from-pink-400 to-pink-600' }
    ]
  },
  {
    year: '4ème année',
    totalQuestions: 287,
    moduleCount: 1,
    modules: [
    { id: 12, title: 'Anatomo-pathologie 2', questionCount: 287, chapterCount: 18, gradient: 'from-indigo-400 to-indigo-600' }
    ]
  },
];

export const totalQuestions = 6137;
export const totalModules = 13;
export const totalYears = 4;
