// Auto-generated by scripts/generate_content_page.py
// Run the script to update this file with the latest module data.

export interface YearModule {
  id: number;
  title: string;
  questionCount: number;
  chapterCount: number;
  gradient: string;
}

export interface YearData {
  year: string;
  totalQuestions: number;
  moduleCount: number;
  modules: YearModule[];
}

export const yearData: YearData[] = [
  {
    year: '1ère année',
    totalQuestions: 1809,
    moduleCount: 4,
    modules: [
    { id: 7, title: 'Histologie Embryologie', questionCount: 125, chapterCount: 19, gradient: 'from-blue-400 to-blue-600' },
    { id: 8, title: 'Anatomie 2', questionCount: 513, chapterCount: 20, gradient: 'from-green-400 to-green-600' },
    { id: 9, title: 'Physiologie 1', questionCount: 679, chapterCount: 30, gradient: 'from-purple-400 to-purple-600' },
    { id: 10, title: 'Hématologie', questionCount: 492, chapterCount: 32, gradient: 'from-red-400 to-red-600' }
    ]
  },
  {
    year: '2ème année',
    totalQuestions: 2274,
    moduleCount: 5,
    modules: [
    { id: 1, title: 'Pharmacologie', questionCount: 612, chapterCount: 31, gradient: 'from-blue-400 to-blue-600' },
    { id: 3, title: 'Anatomo-pathologie 1', questionCount: 266, chapterCount: 20, gradient: 'from-purple-400 to-purple-600' },
    { id: 4, title: 'Sémiologie 2', questionCount: 648, chapterCount: 44, gradient: 'from-green-400 to-green-600' },
    { id: 5, title: 'Radiologie', questionCount: 451, chapterCount: 33, gradient: 'from-red-400 to-red-600' },
    { id: 6, title: 'Biochimie clinique', questionCount: 297, chapterCount: 22, gradient: 'from-yellow-400 to-yellow-600' }
    ]
  },
  {
    year: '3ème année',
    totalQuestions: 2144,
    moduleCount: 4,
    modules: [
    { id: 1, title: 'Pharmacologie', questionCount: 612, chapterCount: 31, gradient: 'from-blue-400 to-blue-600' },
    { id: 2, title: 'Cardiologie', questionCount: 815, chapterCount: 40, gradient: 'from-green-400 to-green-600' },
    { id: 3, title: 'Anatomo-pathologie 1', questionCount: 266, chapterCount: 20, gradient: 'from-purple-400 to-purple-600' },
    { id: 5, title: 'Radiologie', questionCount: 451, chapterCount: 33, gradient: 'from-red-400 to-red-600' }
    ]
  },
];

export const totalQuestions = 4898;
export const totalModules = 10;
export const totalYears = 3;
