#!/usr/bin/env python3
"""Generate the /contenu page data from module JSON files.

Run this script before deploying to Vercel to update the content page
with the latest module information (question counts, chapters, etc.).

Usage:
    python3 scripts/generate_content_page.py
"""

import json
import os
import re

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MODULES_TS_PATH = os.path.join(BASE_DIR, 'src', 'data', 'modules', 'index.ts')
MODULES_JSON_DIR = os.path.join(BASE_DIR, 'src', 'data', 'modules')
DATA_OUTPUT_PATH = os.path.join(BASE_DIR, 'src', 'app', 'contenu', 'contenu-data.ts')

YEAR_ORDER = [
    '1ère année', '2ème année', '3ème année',
    '4ème année', '5ème année', '6ème année', '7ème année',
]


def parse_modules_from_ts(filepath):
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()

    match = re.search(
        r'export const modules:\s*Module\[\]\s*=\s*\[([\s\S]*?)\];',
        content,
    )
    if not match:
        raise ValueError("Could not find modules array in TypeScript file")

    modules_str = match.group(1)

    modules = []
    module_pattern = re.compile(
        r'\{\s*id:\s*(\d+),\s*'
        r"title:\s*'([^']+)',\s*"
        r"subtitle:\s*'([^']+)',\s*"
        r"description:\s*'([^']*)',\s*"
        r"levels:\s*\[([^\]]*)\],\s*"
        r"gradient:\s*'([^']+)',?\s*"
        r"(?:json_filename:\s*'([^']+)',?\s*)?"
        r"(?:icon:\s*'([^']+)',?\s*)?"
        r'\}',
    )

    for m in module_pattern.finditer(modules_str):
        levels_str = m.group(5)
        levels = [
            l.strip().strip("'\"")
            for l in levels_str.split(',')
            if l.strip()
        ]
        module = {
            'id': int(m.group(1)),
            'title': m.group(2),
            'subtitle': m.group(3),
            'description': m.group(4),
            'levels': levels,
            'gradient': m.group(6),
            'json_filename': m.group(7) if m.group(7) else None,
        }
        modules.append(module)

    return modules


def compute_module_stats(modules, json_dir):
    stats = {}
    for module in modules:
        filename = module.get('json_filename') or module['title']
        filepath = os.path.join(json_dir, f'{filename}.json')

        if not os.path.exists(filepath):
            print(f"  WARNING: JSON file not found for '{module['title']}': {filepath}")
            stats[module['id']] = {'questionCount': 0, 'chapterCount': 0}
            continue

        with open(filepath, 'r', encoding='utf-8') as f:
            questions = json.load(f)

        question_count = len(questions)

        subtopics = set()
        for q in questions:
            subtopic = q.get('Subtopic', '').strip()
            if subtopic:
                subtopics.add(subtopic)

        chapter_count = len(subtopics)

        stats[module['id']] = {
            'questionCount': question_count,
            'chapterCount': chapter_count,
        }

    return stats


def generate_data_file(modules, stats):
    years_data = {}
    all_years = set()
    for module in modules:
        for level in module['levels']:
            all_years.add(level)

    for year in all_years:
        year_modules = []
        for module in modules:
            if year in module['levels']:
                year_modules.append(module)
        total_q = sum(stats[m['id']]['questionCount'] for m in year_modules)
        years_data[year] = {
            'modules': year_modules,
            'totalQuestions': total_q,
        }

    sorted_years = sorted(
        all_years,
        key=lambda y: YEAR_ORDER.index(y) if y in YEAR_ORDER else 99,
    )

    total_questions = sum(stats[m['id']]['questionCount'] for m in modules)
    total_modules = len(modules)
    total_years = len(all_years)

    lines = []
    lines.append('// Auto-generated by scripts/generate_content_page.py')
    lines.append('// Run the script to update this file with the latest module data.')
    lines.append('')
    lines.append('export interface YearModule {')
    lines.append('  id: number;')
    lines.append("  title: string;")
    lines.append('  questionCount: number;')
    lines.append('  chapterCount: number;')
    lines.append("  gradient: string;")
    lines.append('}')
    lines.append('')
    lines.append('export interface YearData {')
    lines.append("  year: string;")
    lines.append('  totalQuestions: number;')
    lines.append('  moduleCount: number;')
    lines.append('  modules: YearModule[];')
    lines.append('}')
    lines.append('')
    lines.append('export const yearData: YearData[] = [')

    for year in sorted_years:
        data = years_data[year]
        module_entries = []
        for m in data['modules']:
            s = stats[m['id']]
            module_entries.append(
                f"    {{ id: {m['id']}, title: '{escape_str(m['title'])}', "
                f"questionCount: {s['questionCount']}, "
                f"chapterCount: {s['chapterCount']}, "
                f"gradient: '{m['gradient']}' }}"
            )
        modules_str = ',\n'.join(module_entries)
        lines.append('  {')
        lines.append(f"    year: '{escape_str(year)}',")
        lines.append(f'    totalQuestions: {data["totalQuestions"]},')
        lines.append(f'    moduleCount: {len(data["modules"])},')
        lines.append('    modules: [')
        lines.append(modules_str)
        lines.append('    ]')
        lines.append('  },')

    lines.append('];')
    lines.append('')
    lines.append(f'export const totalQuestions = {total_questions};')
    lines.append(f'export const totalModules = {total_modules};')
    lines.append(f'export const totalYears = {total_years};')

    return '\n'.join(lines) + '\n'


def escape_str(s):
    return s.replace("'", "\\'")


def main():
    print("Parsing module definitions...")
    modules = parse_modules_from_ts(MODULES_TS_PATH)
    print(f"Found {len(modules)} modules")

    print("Computing module statistics...")
    stats = compute_module_stats(modules, MODULES_JSON_DIR)
    for m in modules:
        s = stats[m['id']]
        print(f"  {m['title']}: {s['questionCount']} questions, {s['chapterCount']} chapters")

    print("Generating content data file...")
    os.makedirs(os.path.dirname(DATA_OUTPUT_PATH), exist_ok=True)

    content = generate_data_file(modules, stats)
    with open(DATA_OUTPUT_PATH, 'w', encoding='utf-8') as f:
        f.write(content)
    print(f"Written: {DATA_OUTPUT_PATH}")

    print("Done! Content page data generated successfully.")


if __name__ == '__main__':
    main()